CREATE TABLE SOURCE_SCHEMA.EMPLOYEE (
    EMPNO CHARACTER(6),
    WORKDEPT CHARACTER(3),
    EDLEVEL SMALLINT,
    SEX CHARACTER(1),
    BIRTHDATE DATE,
    SALARY DECIMAL(9,2),
    BONUS DECIMAL(9,2),
    COMM DECIMAL(9,2)
);

CREATE TABLE TARGET_SCHEMA.EMPLOYEE (
    EMPNO CHARACTER(6),
    WORKDEPT CHARACTER(3),
    EDLEVEL SMALLINT,
    SEX CHARACTER(1),
    BIRTHDATE DATE,
    SALARY DECIMAL(9,2),
    BONUS DECIMAL(9,2),
    COMM DECIMAL(9,2)
);
