DB2_SCHEMA_LIST_SQL = "SELECT SCHEMANAME FROM SYSCAT.SCHEMATA"
DB2_TABLE_LIST_SQL = "SELECT TABNAME FROM SYSCAT.TABLES WHERE TABSCHEMA = ?"
DB2_COLUMN_LIST_SQL = "SELECT COLNAME FROM SYSCAT.COLUMNS WHERE TABSCHEMA = ? AND TABNAME = ?"

TERADATA_SCHEMA_LIST_SQL = "SELECT DATABASENAME FROM DBC.DATABASES WHERE DATABASENAME NOT LIKE 'SYS%'"
TERADATA_TABLE_LIST_SQL = "SELECT TABLENAME FROM DBC.TABLES WHERE DATABASENAME = ?"
TERADATA_COLUMN_LIST_SQL = """
SELECT ColumnName FROM DBC.ColumnsV
WHERE DatabaseName = ? AND TableName = ?
ORDER BY ColumnId
"""
